spring:
  application:
     name: Portfolio API
     version: v1.0.0
  data:
     mongodb:
        uri: mongodb://portfolio:portfolio123@localhost:27017
        database: portDb
server:
  port: 9000

